#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP-1 -d 1 2 3 4 5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config border_width         0
bspc config window_gap           16
bspc config split_ratio          0.518
bspc config top_padding          34
bspc config normal_border_color "#2e3440"
bspc config focused_border_color "#2e3440"

bspc rule -a Zathura state-tiled

#AutoStart 
picom &
feh --bg-fill -randomize ~/Pictures/nord.jpg &
~/.config/polybar/launch.sh --hack &
gsettings set org.gnome.desktop.interface gtk-theme "Nordic" &
gsettings set org.gnome.desktop.wm.preferences theme "Nordic" &
setxkbmap br 

